env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - react-app
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  no-console: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  react/prop-types: 0
  react/jsx-filename-extension: [0, { "extensions": [".js", ".jsx"] }]
  react/function-component-definition: 0